name: pft_scavenger_hunt
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.7.0
  animations: ^2.0.11

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Don't need to list each assets image as long is it's in the folder below
    # Thanks! I didn't know this was a thing.
    - assets/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proximanova_black.otf
          weight: 700
        - asset: assets/fonts/proximanova_black.ttf
          weight: 700
        - asset: assets/fonts/proximanova_blackit.otf
          weight: 700
        - asset: assets/fonts/proximanova_bold.otf
          style: italic
        - asset: assets/fonts/proximanova_boldit.otf
          weight: 700
        - asset: assets/fonts/proximanova_extrabold.otf
          weight: 700
        - asset: assets/fonts/proximanova_light.otf
          weight: 700
        - asset: assets/fonts/proximanova_regular.ttf
          weight: 700
        - asset: assets/fonts/ProximaNova-Regular.otf
          weight: 700
